function(_steamworks_auto_copy_runtime)
    set(_files ${ARGN})
    if(NOT _files)
        return()
    endif()

    set(_existing_files "")
    foreach(_file IN LISTS _files)
        if(EXISTS "${_file}")
            list(APPEND _existing_files "${_file}")
        endif()
    endforeach()

    if(NOT _existing_files)
        return()
    endif()

    if(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
        set(_destinations "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    elseif(CMAKE_CONFIGURATION_TYPES)
        set(_destinations "")
        foreach(_config IN LISTS CMAKE_CONFIGURATION_TYPES)
            list(APPEND _destinations "${CMAKE_BINARY_DIR}/${_config}")
        endforeach()
    else()
        set(_destinations "${CMAKE_BINARY_DIR}")
    endif()

    foreach(_dest IN LISTS _destinations)
        file(COPY ${_existing_files} DESTINATION "${_dest}")
    endforeach()

    list(LENGTH _destinations _num_dests)
    if(_num_dests GREATER 1)
        message(STATUS "Steamworks: Copied runtime libraries to ${_num_dests} configuration directories under ${CMAKE_BINARY_DIR}")
    else()
        message(STATUS "Steamworks: Copied runtime libraries to ${_destinations}")
    endif()
endfunction()
